Sprint 2/step 2
meridos/yandex-practicum pull request #3
Opened 2023-04-23 19:32 UTC by meridos

2023-04-23 20:07 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Редьюсеры чистые функции
- `Dnd` работает хорошо
- Созданы все необходимые экшены
- Хорошая организация хранилища

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- При добавлении булок не меняется цена и сами булки не попадают payload запроса на номер заказа.

<img width="1440" alt="Снимок экрана 2023-04-23 в 22 54 37" src="https://user-images.githubusercontent.com/60173362/233862272-7cb79e2a-db8c-48a7-818e-c0f6fc9531e6.png">
<img width="420" alt="Снимок экрана 2023-04-23 в 22 54 27" src="https://user-images.githubusercontent.com/60173362/233862276-155bdc61-31ad-48ac-8a6c-9355dc5c6415.png"> 

- Вы забыли указать массив зависимостей для `useCallback`
-  `key={id + i}` на 73 строчке в конструкторе необходимо удалить. Для атрибута `key` в конструкторе нужно использовать для ингредиента уникальный `uuid`. (Вам нужно его генерировать во время сброса в зону `DnD`). Это можно делать с помощью библиотеки uuid https://www.npmjs.com/package/uuid , или Вам должны были показать, как это сделать, иначе некорректно может работать DND. А в key будет уже просто `key={ item.uuid }`

**Можно лучше**
- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты
- лучше не давать нажать на кнопку Оформить заказ, пока пользователь не добавил булку в заказ.
- Дополнительно хранить в сторе список ингредиентов, которые попали в заказ - не нужно, это в будущем не пригодится.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-23 20:07 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  const overlayError = useSelector((state) => state.error.overlayError);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-04-23 20:07 UTC, andryxxa93 commented on src/components/order/order.jsx
>    const onCompleteClick = useCallback(() => {
**Необходимо исправить**
Вы забыли указать массив зависимостей для `useCallback`

2023-04-23 20:07 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +              <React.Fragment key={id + i}>
**Необходимо исправить**
` key={id + i}` нужно удалить. для атрибута `key` в конструкторе нужно использовать для ингредиента уникальный `uuid` (Вам нужно его генерировать во время сброса в зону `DnD`). Это можно делать с помощью библиотеки uuid https://www.npmjs.com/package/uuid , или Вам должны были показать, как это сделать, иначе некорректно может работать DND. А в key будет уже просто `key={ item.uuid }`

2023-04-27 08:47 UTC, meridos commented on src/components/burger-constructor/burger-constructor.jsx
> +              <React.Fragment key={id + i}>
Исправил
https://github.com/meridos/yandex-practicum/pull/3/commits/fc6b4d1db833a1203bf513d9fed898db9650000f

2023-04-27 08:47 UTC, meridos commented on src/components/order/order.jsx
>    const onCompleteClick = useCallback(() => {
Исправил
https://github.com/meridos/yandex-practicum/pull/3/commits/a0089803a6aa6102bc474253291e66b52954b09d

2023-04-27 08:48 UTC, meridos commented on src/components/app/app.jsx
> +  const overlayError = useSelector((state) => state.error.overlayError);
Спасибо, заменил
https://github.com/meridos/yandex-practicum/pull/3/commits/fdbe9411bcdfb0533b9893ce79a1c4580d8ac465

2023-04-27 18:31 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-27 19:05 UTC, merged