Sprint 3/step 1
meridos/yandex-practicum pull request #4
Opened 2023-05-13 01:06 UTC by meridos

2023-05-13 05:23 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Показываете ошибки запроса
- Настроены все редиректы
- Хорошая работа с формами и куками

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.
Для проверки ответа можете создать функцию, которая принимает `url` и опции запроса (хедеры и.т.п). Эта функция должна сначала сделать запрос по адресу с опциями, если запрос падает с ошибкой  `jwt-expired`, то нужно обновить accessToken с помощью refreshToken. После обновления необходимо просто повторить ранее неудавшийся запрос, но используя уже свежий токен.
- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx . Пожалуйста, посоветуйтесь с наставником.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-13 05:23 UTC, andryxxa93 commented on src/components/app/app.jsx
> +              path="/forgot-password"
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-05-13 11:55 UTC, meridos commented on src/components/app/app.jsx
> +              path="/forgot-password"
Переместил
https://github.com/meridos/yandex-practicum/pull/4/commits/dfb86322e65bd8ca6d6dcdc3af21d630f5288211

2023-05-13 15:37 UTC, andryxxa93 requested changes
Всё отлично, но одна проблема есть теперь - при открытии по прямой ссылке деталей ингредиента отображается 404 страница. Необходимо делать запрос и получать необходимый ингредиент, судя по вкладке network - этого не происходит.

<img width="1440" alt="Снимок экрана 2023-05-13 в 18 36 20" src="https://github.com/meridos/yandex-practicum/assets/60173362/a8b094e2-c06f-4103-9036-43a8de629e72">

2023-05-14 08:26 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-19 17:33 UTC, merged